version: '3'
name: hab-eat

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '433:433'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  hab-eat:
    build: .
    container_name: hab-eat
    ports:
      - '3000:3000'
    env_file:
      - .env
