name: Build and Push Docker Image
on:
  push:
    branches:
      - production
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_TAGS }}

      - name: Generate deployment package
        run: zip deploy.zip docker-compose.yml nginx.conf

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          deployment_package: deploy.zip
          version_label: api-server-deploy
          use_existing_version_if_available: true
          wait_for_environment_recovery: 180
